apiVersion: v1
kind: Service
metadata:
  name: tienda-backend-despachos
  namespace: tienda
spec:
  selector:
    app: tienda-backend-despachos
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
